'use client';
import Image from 'next/image';
import { FormEvent, useState } from 'react';
import type { MediaItem } from '@/types/content';

export function MediaManager({ initialMedia }: { initialMedia: MediaItem[] }) {
  const [media,setMedia]=useState(initialMedia); const [message,setMessage]=useState(''); const [uploading,setUploading]=useState(false);
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setUploading(true);setMessage('');const form=e.currentTarget;const fd=new FormData(form);const res=await fetch('/api/admin/media/upload',{method:'POST',body:fd});const body=await res.json().catch(()=>({}));setUploading(false);if(res.ok){setMedia(m=>[body.item,...m]);setMessage('Image uploaded and optimized.');form.reset()}else setMessage(body.error||'Upload failed.')}
  async function save(item:MediaItem){const res=await fetch(`/api/admin/media/${item.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});setMessage(res.ok?'Media SEO details saved.':'Could not save media details.')}
  return <><div className="adminCard"><span className="eyebrow">Media Library</span><h1 style={{fontSize:'2rem'}}>Upload Images</h1><p className="notice">Uploads are renamed with SEO-friendly filenames, resized when needed, stripped of unnecessary metadata and converted to WebP. Review the automatically generated alt text before publishing.</p><form onSubmit={upload} className="formGrid" style={{marginTop:16}}><div className="field"><label htmlFor="image">Image</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></div><div className="field"><label htmlFor="alt">Alt text (optional)</label><input id="alt" name="alt" placeholder="Describe the image in context"/></div><div className="field fieldFull"><button className="btn btnPrimary" type="submit" disabled={uploading}>{uploading?'Optimizing…':'Upload & Optimize'}</button></div></form>{message&&<p className="statusMessage">{message}</p>}</div><div className="mediaGrid" style={{marginTop:20}}>{media.map((item,index)=><MediaCard item={item} key={item.id} onChange={next=>setMedia(list=>list.map(x=>x.id===next.id?next:x))} onSave={save} priority={index<3}/>)}</div></>
}
function MediaCard({item,onChange,onSave,priority}:{item:MediaItem;onChange:(item:MediaItem)=>void;onSave:(item:MediaItem)=>void;priority:boolean}){return <article className="adminCard mediaCard"><Image src={item.url} alt={item.alt} width={item.width||800} height={item.height||600} priority={priority} sizes="(max-width: 900px) 100vw, 300px"/><div className="mediaMeta"><strong>{item.filename}</strong><label>Alt text<input value={item.alt} onChange={e=>onChange({...item,alt:e.target.value})}/></label><label>Title<input value={item.title} onChange={e=>onChange({...item,title:e.target.value})}/></label><label>Caption<textarea value={item.caption} onChange={e=>onChange({...item,caption:e.target.value})}/></label><button className="buttonSmall" type="button" onClick={()=>onSave(item)}>Save SEO Details</button></div></article>}
