'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { ContentBlock, MediaItem, Post } from '@/types/content';

function uid(){return crypto.randomUUID()}
function slugifyClient(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)}
function blankBlock(type:ContentBlock['type']):ContentBlock{
  if(type==='list') return {id:uid(),type:'list',items:['']};
  if(type==='button') return {id:uid(),type:'button',text:'Learn More',url:'/contact'};
  if(type==='image') return {id:uid(),type:'image',url:'',alt:'',caption:''};
  return {id:uid(),type,text:''} as ContentBlock;
}

export function PostEditor({initialPost,media,categories,tags}:{initialPost:Post;media:MediaItem[];categories:string[];tags:string[]}){
  const router=useRouter();
  const [post,setPost]=useState(initialPost); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const [titlePx,setTitlePx]=useState(0); const [descPx,setDescPx]=useState(0);
  useEffect(()=>{const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d');if(!ctx)return;ctx.font='600 20px Arial';setTitlePx(Math.round(ctx.measureText(post.metaTitle||post.title).width));ctx.font='400 14px Arial';setDescPx(Math.round(ctx.measureText(post.metaDescription).width));},[post.metaTitle,post.metaDescription,post.title]);
  const keyword=(post.focusKeyword||'').toLowerCase();
  const seoChecks=useMemo(()=>[
    ['Keyword in title',!keyword||post.title.toLowerCase().includes(keyword)],
    ['Keyword in URL',!keyword||post.slug.includes(slugifyClient(keyword))],
    ['Keyword in meta title',!keyword||(post.metaTitle||post.title).toLowerCase().includes(keyword)],
    ['Keyword in description',!keyword||post.metaDescription.toLowerCase().includes(keyword)],
    ['Featured image alt',!post.featuredImage||Boolean(post.featuredAlt.trim())]
  ] as const,[keyword,post]);
  function update<K extends keyof Post>(key:K,value:Post[K]){setPost(prev=>({...prev,[key]:value,updatedAt:new Date().toISOString()}))}
  function updateBlock(index:number,next:ContentBlock){setPost(prev=>({...prev,blocks:prev.blocks.map((b,i)=>i===index?next:b)}))}
  function move(index:number,dir:-1|1){setPost(prev=>{const blocks=[...prev.blocks];const to=index+dir;if(to<0||to>=blocks.length)return prev;[blocks[index],blocks[to]]=[blocks[to],blocks[index]];return {...prev,blocks}})}
  async function save(status:Post['status']){setSaving(true);setMessage('');const payload={...post,status,publishedAt:status==='published'?(post.publishedAt||new Date().toISOString()):post.publishedAt};const res=await fetch(post.id?`/api/admin/posts/${post.id}`:'/api/admin/posts',{method:post.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));setSaving(false);if(res.ok){setPost(body.post);setMessage('Saved successfully.');if(!initialPost.id)router.replace(`/admin/posts/${body.post.id}`);router.refresh()}else setMessage(body.error||'Save failed.')}
  return <div className="editorLayout"><div className="editorPanel"><div className="adminCard"><span className="eyebrow">Post Editor</span><input aria-label="Post title" value={post.title} onChange={e=>{const title=e.target.value;setPost(p=>({...p,title,slug:p.slug||slugifyClient(title)}))}} placeholder="Post title" style={{width:'100%',fontSize:'2rem',fontWeight:700,border:0,outline:0,padding:'8px 0'}}/><textarea value={post.excerpt} onChange={e=>update('excerpt',e.target.value)} placeholder="Short excerpt" style={{width:'100%',minHeight:90,border:'1px solid #ddd',borderRadius:10,padding:12}}/></div>
  {post.blocks.map((block,index)=><div className="editorBlock" key={block.id}><div className="blockToolbar"><strong>{block.type}</strong><div className="adminActions"><button className="buttonSmall" type="button" onClick={()=>move(index,-1)}>↑</button><button className="buttonSmall" type="button" onClick={()=>move(index,1)}>↓</button><button className="buttonSmall buttonDanger" type="button" onClick={()=>setPost(p=>({...p,blocks:p.blocks.filter((_,i)=>i!==index)}))}>Remove</button></div></div>{(['paragraph','h2','h3','quote'] as const).includes(block.type as never)&&'text' in block&&<textarea value={block.text} onChange={e=>updateBlock(index,{...block,text:e.target.value} as ContentBlock)}/>} {block.type==='list'&&<><textarea value={block.items.join('\n')} onChange={e=>updateBlock(index,{...block,items:e.target.value.split('\n')})}/><p className="small">One list item per line</p></>} {block.type==='button'&&<div className="formGrid"><div className="field"><label>Button text</label><input value={block.text} onChange={e=>updateBlock(index,{...block,text:e.target.value})}/></div><div className="field"><label>URL</label><input value={block.url} onChange={e=>updateBlock(index,{...block,url:e.target.value})}/></div></div>} {block.type==='image'&&<div className="formGrid"><div className="field fieldFull"><label>Image</label><select value={block.url} onChange={e=>{const m=media.find(x=>x.url===e.target.value);updateBlock(index,{...block,url:e.target.value,alt:block.alt||m?.alt||''})}}><option value="">Choose media</option>{media.map(m=><option key={m.id} value={m.url}>{m.title||m.filename}</option>)}</select></div><div className="field"><label>Alt text</label><input value={block.alt} onChange={e=>updateBlock(index,{...block,alt:e.target.value})}/></div><div className="field"><label>Caption</label><input value={block.caption||''} onChange={e=>updateBlock(index,{...block,caption:e.target.value})}/></div></div>}</div>)}
  <div className="adminCard"><strong>Add block</strong><div className="adminActions" style={{marginTop:12}}>{(['paragraph','h2','h3','list','quote','image','button'] as ContentBlock['type'][]).map(type=><button key={type} className="buttonSmall" type="button" onClick={()=>update('blocks',[...post.blocks,blankBlock(type)])}>{type}</button>)}</div></div></div>
  <aside className="editorAside"><div className="adminCard"><h3>Publish</h3><div className="field"><label>Status</label><select value={post.status} onChange={e=>update('status',e.target.value as Post['status'])}><option value="draft">Draft</option><option value="published">Published</option></select></div><div className="adminActions" style={{marginTop:14}}><button className="btn btnSecondary" type="button" disabled={saving} onClick={()=>save('draft')}>Save Draft</button><button className="btn btnPrimary" type="button" disabled={saving} onClick={()=>save('published')}>Publish</button></div>{message&&<p className="statusMessage">{message}</p>}</div>
  <div className="adminCard"><h3>URL</h3><div className="field"><label>Slug</label><input value={post.slug} onChange={e=>update('slug',slugifyClient(e.target.value))}/></div><p className="small">/blog/{post.slug||'post-slug'}</p></div>
  <div className="adminCard"><h3>Featured Image</h3><div className="field"><select value={post.featuredImage} onChange={e=>{const m=media.find(x=>x.url===e.target.value);setPost(p=>({...p,featuredImage:e.target.value,featuredAlt:m?.alt||p.featuredAlt}))}}><option value="">No featured image</option>{media.map(m=><option key={m.id} value={m.url}>{m.title||m.filename}</option>)}</select></div><div className="field"><label>Featured image alt</label><input value={post.featuredAlt} onChange={e=>update('featuredAlt',e.target.value)}/></div></div>
  <div className="adminCard"><h3>Categories</h3><div className="checkboxList">{categories.map(c=><label className="checkboxPill" key={c}><input type="checkbox" checked={post.categories.includes(c)} onChange={e=>update('categories',e.target.checked?[...post.categories,c]:post.categories.filter(x=>x!==c))}/>{c}</label>)}</div><h3 style={{marginTop:18}}>Tags</h3><div className="checkboxList">{tags.map(t=><label className="checkboxPill" key={t}><input type="checkbox" checked={post.tags.includes(t)} onChange={e=>update('tags',e.target.checked?[...post.tags,t]:post.tags.filter(x=>x!==t))}/>{t}</label>)}</div></div>
  <div className="adminCard"><h3>SEO</h3><div className="field"><label>Focus keyword</label><input value={post.focusKeyword} onChange={e=>update('focusKeyword',e.target.value)}/></div><div className="field"><label>Meta title</label><input value={post.metaTitle} onChange={e=>update('metaTitle',e.target.value)}/><span className="small">{(post.metaTitle||post.title).length} chars • ~{titlePx}px</span></div><div className="field"><label>Meta description</label><textarea value={post.metaDescription} onChange={e=>update('metaDescription',e.target.value)}/><span className="small">{post.metaDescription.length} chars • ~{descPx}px</span></div><div className="seoMeter">{seoChecks.map(([label,ok])=><div key={label} className={ok?'meterGood':'meterWarn'}>{ok?'✓':'•'} {label}</div>)}</div></div>
  <div className="adminCard"><h3>Schema</h3><div className="field"><label>Schema type</label><select value={post.schemaType} onChange={e=>update('schemaType',e.target.value as Post['schemaType'])}><option>BlogPosting</option><option>Article</option><option>FAQPage</option><option>HowTo</option></select></div><h3 style={{marginTop:18}}>FAQ schema</h3>{post.faqs.map((faq,index)=><div key={index} className="editorBlock"><div className="field"><label>Question</label><input value={faq.question} onChange={e=>update('faqs',post.faqs.map((f,i)=>i===index?{...f,question:e.target.value}:f))}/></div><div className="field"><label>Answer</label><textarea value={faq.answer} onChange={e=>update('faqs',post.faqs.map((f,i)=>i===index?{...f,answer:e.target.value}:f))}/></div><button className="buttonSmall buttonDanger" type="button" onClick={()=>update('faqs',post.faqs.filter((_,i)=>i!==index))}>Remove FAQ</button></div>)}<button className="buttonSmall" type="button" onClick={()=>update('faqs',[...post.faqs,{question:'',answer:''}])}>Add FAQ</button><div className="field" style={{marginTop:16}}><label>Custom JSON-LD (optional)</label><textarea value={post.customSchema||''} onChange={e=>update('customSchema',e.target.value)} placeholder='{"@context":"https://schema.org"}'/></div></div></aside></div>
}
