'use client';
import { FormEvent, useState } from 'react';

export function TaxonomyManager({initialCategories,initialTags}:{initialCategories:string[];initialTags:string[]}){
  const [categories,setCategories]=useState(initialCategories);const [tags,setTags]=useState(initialTags);const [message,setMessage]=useState('');
  async function save(){const res=await fetch('/api/admin/taxonomy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({categories,tags})});setMessage(res.ok?'Categories and tags saved.':'Could not save taxonomy.')}
  function add(e:FormEvent<HTMLFormElement>,kind:'category'|'tag'){e.preventDefault();const fd=new FormData(e.currentTarget);const value=String(fd.get('value')||'').trim();if(!value)return;if(kind==='category')setCategories(v=>Array.from(new Set([...v,value])));else setTags(v=>Array.from(new Set([...v,value])));e.currentTarget.reset()}
  return <div className="grid2"><div className="adminCard"><span className="eyebrow">Taxonomy</span><h1 style={{fontSize:'2rem'}}>Categories</h1><form onSubmit={e=>add(e,'category')} className="adminActions"><input name="value" placeholder="New category" style={{flex:1,padding:10,border:'1px solid #ddd',borderRadius:9}}/><button className="buttonSmall">Add</button></form><div className="checkboxList" style={{marginTop:18}}>{categories.map(c=><span className="checkboxPill" key={c}>{c}<button type="button" aria-label={`Remove ${c}`} onClick={()=>setCategories(v=>v.filter(x=>x!==c))} style={{border:0,background:'transparent',cursor:'pointer'}}>×</button></span>)}</div></div><div className="adminCard"><span className="eyebrow">Taxonomy</span><h2>Tags</h2><form onSubmit={e=>add(e,'tag')} className="adminActions"><input name="value" placeholder="New tag" style={{flex:1,padding:10,border:'1px solid #ddd',borderRadius:9}}/><button className="buttonSmall">Add</button></form><div className="checkboxList" style={{marginTop:18}}>{tags.map(t=><span className="checkboxPill" key={t}>{t}<button type="button" aria-label={`Remove ${t}`} onClick={()=>setTags(v=>v.filter(x=>x!==t))} style={{border:0,background:'transparent',cursor:'pointer'}}>×</button></span>)}</div><div className="btnRow"><button className="btn btnPrimary" type="button" onClick={save}>Save Changes</button></div>{message&&<p className="statusMessage">{message}</p>}</div></div>
}
